import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import Table from "../components/table";
import styles from "../styles/Home.module.css";
import { PrismaClient } from "@prisma/client";
import ThirdSection from "../components/thirdSection";

// export default function Home({ data }) {
export default function Home() {
	var data = [
		{
			id: 1,
			name: "Plot 1",
			lp: 3200000,
			deltalp: 5,
			hp: 4000000,
			deltahp: 10,
			trend: "up",
		},
		{
			id: 9,
			name: "Plot 2",
			lp: 2500000,
			deltalp: 10,
			hp: 5000000,
			deltahp: 3,
			trend: "up",
		},
		{
			id: 10,
			name: "Plot 3",
			lp: 1500000,
			deltalp: 10,
			hp: 3200000,
			deltahp: 3,
			trend: "up",
		},
		{
			id: 11,
			name: "Plot 4",
			lp: 9400000,
			deltalp: 10,
			hp: 10200000,
			deltahp: 3,
			trend: "down",
		},
		{
			id: 12,
			name: "Plot 5",
			lp: 5800000,
			deltalp: 10,
			hp: 7000000,
			deltahp: 3,
			trend: "up",
		},
		{
			id: 13,
			name: "Plot 6",
			lp: 50000000,
			deltalp: 2,
			hp: 70000000,
			deltahp: 4,
			trend: "up",
		},
		{
			id: 14,
			name: "Plot 7",
			lp: 10000000,
			deltalp: 2,
			hp: 21000000,
			deltahp: 4,
			trend: "up",
		},
		{
			id: 15,
			name: "Plot 8",
			lp: 13000000,
			deltalp: 10,
			hp: 29000000,
			deltahp: 15,
			trend: "up",
		},
		{
			id: 16,
			name: "Plot 9",
			lp: 12000000,
			deltalp: 10,
			hp: 15000000,
			deltahp: 15,
			trend: "up",
		},
		{
			id: 17,
			name: "Plot 10",
			lp: 8700000,
			deltalp: 10,
			hp: 9200000,
			deltahp: 15,
			trend: "down",
		},
	];

	return (
		<div className={styles.wrapper}>
			<div className={styles.container}>
				<Head>
					<title>Precincts</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
					<link rel="preconnect" href="https://fonts.googleapis.com" />
					<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
					<link
						href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
						rel="stylesheet"
					/>
				</Head>
				<Header />
				<Table data={data} />
				<ThirdSection />
			</div>
		</div>
	);
}
// export const getServerSideProps = async ({ req }) => {
// 	const prisma = new PrismaClient();
// 	const data = await prisma.housing.findMany();
// 	return { props: { data } };
// };
